---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name="{{ packages }}" state=present
  become: yes
  vars:
    packages:
      - wget
      - curl
