---
- name: Set MariaDB root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mariadb.root_pass | quote}}' vtype='password'

- name: Confirm MariaDB root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mariadb.root_pass | quote}}' vtype='password'

- name: Install MariaDB
  apt: package={{ packages }} state=present
  become: yes
  vars:
    packages:
      - mariadb-server
      - mariadb-client
      - python-mysqldb

- name: Start the MariaDB service
  become: yes
  action: service name=mysql state=started

- name: Deletes anonymous MariaDB server user for localhost
  mysql_user: user="" state="absent" login_password="{{ mariadb.root_pass }}" login_user=root

- name: Secures the MariaDB root user
  mysql_user: user="root" password="{{ mariadb.root_pass }}" host="{{ item }}" login_password="{{mariadb.root_pass}}" login_user=root
  with_items:
    - 127.0.0.1
    - localhost
    - ::1

- name: Removes the MariaDB test database
  mysql_db: db=test state=absent login_password="{{ mariadb.root_pass }}" login_user=root
